# Generated by Django 4.0 on 2022-01-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('votes', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('filepath', models.CharField(max_length=200)),
                ('approved', models.DateTimeField(default='null')),
            ],
        ),
    ]
