# Generated by Django 4.0 on 2022-01-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='media',
            field=models.FileField(default='null', upload_to='generictimeline/media/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='approved',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
