# Generated by Django 4.0 on 2022-01-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_alter_video_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
