# Generated by Django 4.0 on 2022-01-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_alter_video_approved_alter_video_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='media',
            field=models.FileField(upload_to=''),
        ),
    ]
