# Generated by Django 4.0 on 2022-01-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_alter_video_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='filepath',
        ),
    ]
